# Generated by Django 5.1.3 on 2025-03-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Croi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Модель Изделий')),
                ('quentity_detail', models.PositiveIntegerField(default=0, verbose_name='Количество Изделий')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный Кройщик')),
            ],
            options={
                'verbose_name': 'Крой',
                'verbose_name_plural': 'Крой',
            },
        ),
    ]
