# Generated by Django 5.1.3 on 2025-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_croi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
    ]
