services:
  db:
    image: postgres:14
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env
    ports:
      - 5433:5342
    volumes:
      - pg_data:/var/lib/postgresql/data
    
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 10

  web_crm:
    
    build:
      context: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8989:8989"
    env_file:
      - .env
    depends_on:
      - db
 
volumes:
  pg_data:
  static_volume:
  media_volume: