# Generated by Django 5.1.3 on 2025-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logistics', '0001_initial'),
        ('app_productions', '0003_cargo_alter_product_price_alter_product_quentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='product',
            field=models.ManyToManyField(to='app_productions.product', verbose_name='Товары'),
        ),
    ]
