# Generated by Django 5.1.3 on 2025-02-27 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_productions', '0003_cargo_alter_product_price_alter_product_quentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата Начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата Окончание')),
                ('packed', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Упаковано')),
                ('send_cargo', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Отправлено в Карго')),
                ('marriage', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Брак')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('packer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Упаковщик')),
                ('product', models.ManyToManyField(blank=True, to='app_productions.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Производственный Процесс',
                'verbose_name_plural': 'Производственный Процесс',
            },
        ),
    ]
