# Generated by Django 5.1.3 on 2025-03-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_packaging', '0002_productprocess_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprocess',
            options={'verbose_name': 'Процесс Упаковки', 'verbose_name_plural': 'Процесс Упаковки'},
        ),
    ]
