# Generated by Django 5.1.3 on 2025-03-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_productions', '0003_cargo_alter_product_price_alter_product_quentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtugProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата Начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата Окончание')),
                ('done', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Упаковано')),
                ('marriage', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Брак')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_utug', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('product', models.ManyToManyField(blank=True, to='app_productions.product', verbose_name='Товар')),
                ('utujnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Утюжние')),
            ],
        ),
    ]
