# Generated by Django 5.1.3 on 2025-03-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utug', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='utugprocess',
            name='done',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Утюжано'),
        ),
        migrations.AlterField(
            model_name='utugprocess',
            name='utujnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Утюжник'),
        ),
    ]
