# Generated by Django 5.1.3 on 2025-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.PositiveIntegerField(verbose_name='Плановое количество')),
            ],
            options={
                'verbose_name': 'Товар в партии',
                'verbose_name_plural': 'Товары в партии',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Категория Товара',
                'verbose_name_plural': 'Категория Товара',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Цвет Товара',
                'verbose_name_plural': 'Цвет Товара',
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('SEWING', 'Шитье'), ('Utug', 'Утюг'), ('PACKING', 'Упаковка'), ('CUTTING', 'Крой'), ('QC', 'Контроль качества')], max_length=20, verbose_name='Тип этапа')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершено'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата Начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата Окончания')),
                ('quantity_completed', models.PositiveIntegerField(default=0, verbose_name='Выполнено (выход)')),
                ('quantity_defective', models.PositiveIntegerField(default=0, verbose_name='Брак (на этом этапе)')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи этапа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Этап процесса',
                'verbose_name_plural': 'Этапы процессов',
                'ordering': ['batch_product__batch__batch_number', 'batch_product__product__title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('quentity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Product_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Брэнд Товара',
                'verbose_name_plural': 'Брэнд Товара',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Номер партии')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Наименование')),
                ('planned_completion_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата завершения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Партия завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Производственная партия',
                'verbose_name_plural': 'Производственные партии',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Размер Товара',
                'verbose_name_plural': 'Размер Товара',
            },
        ),
    ]
