# Generated by Django 5.1.3 on 2024-12-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='app_productions.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='app_productions.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ManyToManyField(blank=True, to='app_productions.product_model', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='app_productions.size', verbose_name='Размер  '),
        ),
    ]
