# Generated by Django 5.1.3 on 2025-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
