# Generated by Django 5.1.3 on 2024-12-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productions', '0002_alter_product_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_model',
            options={'verbose_name': 'Брэнд Товара', 'verbose_name_plural': 'Брэнд Товара'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер Товара', 'verbose_name_plural': 'Размер Товара'},
        ),
    ]
