# Generated by Django 5.1.3 on 2025-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productions', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coming', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quentity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во'),
        ),
    ]
