# Generated by Django 5.1.3 on 2024-11-14 17:31

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/employees/%Y/%m/%d/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('uuid', models.CharField(blank=True, null=True, unique=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Супер пользователь')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('is_technolog', models.BooleanField(blank=True, default=False, null=True, verbose_name='Технолог')),
                ('is_upakovka', models.BooleanField(default=False, verbose_name='Упаковка')),
                ('is_utug', models.BooleanField(blank=True, default=False, null=True, verbose_name='Утюг')),
                ('is_croi', models.BooleanField(blank=True, default=False, null=True, verbose_name='Крой')),
                ('is_buttons', models.BooleanField(blank=True, default=False, null=True, verbose_name='Пуговица')),
                ('is_tailor', models.BooleanField(blank=True, default=False, null=True, verbose_name='Портной')),
                ('is_povar', models.BooleanField(blank=True, default=False, null=True, verbose_name='Повар')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
