# Generated by Django 5.1.3 on 2024-11-14 17:39

import app_users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app_users.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_buttons',
            field=models.BooleanField(default=False, verbose_name='Пуговица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_croi',
            field=models.BooleanField(default=False, verbose_name='Крой'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_povar',
            field=models.BooleanField(default=False, verbose_name='Повар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tailor',
            field=models.BooleanField(default=False, verbose_name='Портной'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_technolog',
            field=models.BooleanField(default=False, verbose_name='Технолог'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_utug',
            field=models.BooleanField(default=False, verbose_name='Утюг'),
        ),
    ]
