# Generated by Django 5.1.3 on 2025-03-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_historicaluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
