# Generated by Django 5.1.3 on 2024-12-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
