# Generated by Django 5.1.3 on 2025-06-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('status', models.CharField(blank=True, choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], default='INFO', null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'История Логов',
                'verbose_name_plural': 'Истории Логов',
            },
        ),
    ]
