# Generated by Django 5.1.3 on 2025-03-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminhistorylog',
            options={'verbose_name': 'История Логов', 'verbose_name_plural': 'Истории Логов'},
        ),
    ]
