# Generated by Django 5.1.3 on 2025-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0002_alter_adminhistorylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhistorylog',
            name='status',
            field=models.CharField(blank=True, choices=[('INFO', 'INFO'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], default='INFO', null=True, verbose_name='Статус'),
        ),
    ]
